// Code generated by protoc-gen-go.
// source: TestMessage.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	TestMessage.proto

It has these top-level messages:
	TestMessage
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type TestMessage_Event int32

const (
	TestMessage_ConnectionOpen  TestMessage_Event = 0
	TestMessage_ConnectionClose TestMessage_Event = 1
	TestMessage_Data            TestMessage_Event = 2
)

var TestMessage_Event_name = map[int32]string{
	0: "ConnectionOpen",
	1: "ConnectionClose",
	2: "Data",
}
var TestMessage_Event_value = map[string]int32{
	"ConnectionOpen":  0,
	"ConnectionClose": 1,
	"Data":            2,
}

func (x TestMessage_Event) Enum() *TestMessage_Event {
	p := new(TestMessage_Event)
	*p = x
	return p
}
func (x TestMessage_Event) String() string {
	return proto.EnumName(TestMessage_Event_name, int32(x))
}
func (x *TestMessage_Event) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestMessage_Event_value, data, "TestMessage_Event")
	if err != nil {
		return err
	}
	*x = TestMessage_Event(value)
	return nil
}
func (TestMessage_Event) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type TestMessage struct {
	Id               *int32             `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Event            *TestMessage_Event `protobuf:"varint,2,req,name=event,enum=protobuf.TestMessage_Event" json:"event,omitempty"`
	Data             *string            `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *TestMessage) Reset()                    { *m = TestMessage{} }
func (m *TestMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()               {}
func (*TestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestMessage) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TestMessage) GetEvent() TestMessage_Event {
	if m != nil && m.Event != nil {
		return *m.Event
	}
	return TestMessage_ConnectionOpen
}

func (m *TestMessage) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "protobuf.TestMessage")
	proto.RegisterEnum("protobuf.TestMessage_Event", TestMessage_Event_name, TestMessage_Event_value)
}

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x0c, 0x49, 0x2d, 0x2e,
	0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0x49, 0xa5, 0x69, 0x4a, 0xfd, 0x8c, 0x5c, 0xdc, 0x48, 0xf2, 0x42, 0x5c, 0x5c, 0x4c, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0xac, 0x42, 0x5a, 0x5c, 0xac, 0xa9, 0x65, 0xa9, 0x79, 0x25,
	0x12, 0x4c, 0x40, 0x2e, 0x9f, 0x91, 0xb4, 0x1e, 0x4c, 0x97, 0x1e, 0xb2, 0x89, 0xae, 0x20, 0x25,
	0x42, 0x3c, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0xcc, 0x40, 0xa5, 0x9c, 0x4a, 0x56, 0x5c,
	0xac, 0x10, 0x61, 0x21, 0x2e, 0x3e, 0xe7, 0xfc, 0xbc, 0xbc, 0xd4, 0xe4, 0x92, 0xcc, 0xfc, 0x3c,
	0xff, 0x82, 0xd4, 0x3c, 0x01, 0x06, 0x21, 0x61, 0x2e, 0x7e, 0x84, 0x98, 0x73, 0x4e, 0x7e, 0x71,
	0xaa, 0x00, 0xa3, 0x10, 0x07, 0x17, 0x8b, 0x0b, 0x50, 0xbf, 0x00, 0x13, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x6f, 0xbb, 0x01, 0xf8, 0xaf, 0x00, 0x00, 0x00,
}
